export const routes = {
    home: '/',
    about: '/hakkimizda',
    whyUs: '/neden-mba-metal',
    capabilities: '/uretim-kabiliyetleri',
    industries: '/sektorler',
    industryDetail: '/sektorler/:industrySlug',
    automotive: '/sektorler/otomotiv',
    whiteGoods: '/sektorler/beyaz-esya',
    retail: '/sektorler/perakende-magazacilik',
    logistics: '/sektorler/lojistik-tasima',
    industrial: '/sektorler/endustriyel-uretim',
    quality: '/kalite',
    projects: '/projeler',
    contact: '/iletisim',
    quote: '/hizli-teklif',
} as const;