export const routes = {
    home: '/',
    about: '/hakkimizda',
    whyUs: '/neden-mba-metal',
    capabilities: '/uretim-kabiliyetleri',
    industries: '/sektorler',
    industryDetail: '/sektorler/:industrySlug',
    automotive: '/sektorler/otomotiv',
    whiteGoods: '/sektorler/beyaz-esya',
    retail: '/sektorler/perakende-magazacilik',
    logistics: '/sektorler/lojistik-tasima',
    industrial: '/sektorler/endustriyel-uretim',
    defenseAerospaceSecurity: '/sektorler/savunma-havacilik-guvenlik',
    marine: '/sektorler/gemi-denizcilik-liman',
    contact: '/iletisim',
    market: '/pazar',
    furniture: '/sektorler/mobilya',
    medical: '/sektorler/medikal-hijyen-urunleri',
    agriculture: '/sektorler/tarim-hayvancilik',
    construction: '/sektorler/insaat-genel-sanayi',

} as const;